### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [128, 64, 4, 4], expected input[528, 1, 241, 241] to have 128 channels, but got 1 channels instead

### ISSUE THREAD

**Issue by SojeongAn** [czifan/ConvLSTM.pytorch#1]
Hello,
I am trying to integrate your convLSTM cell into my data.
I did this in the following way (Decoder):
![decoder-error-1](https://user-images.githubusercontent.com/39581678/88885695-f3b4b600-d273-11ea-9963-b221e5c21b93.PNG)

but It will report an error halfway through.
Here’s the error:
![decoder-error-2](https://user-images.githubusercontent.com/39581678/88885899-527a2f80-d274-11ea-856f-fab5f966d331.PNG)

As shown above, test_data has the shape: torch.Size([88, 6, 1, 241, 241])

Am I misunderstanding something?
What is supposed to happen here?

Thanks for any help :-D

**Comment by dreamsfly900** [comment]
inputs=torch.Size([2, 10, 1, 128, 128])
outputs=torch.Size([2, 10, 1, 128, 128])
2=batch_size
10=time
 128, 128=data
data=64*64 or 128*128 or 256*256 or 512*512

**Comment by czifan** [comment]
Could you print out the shape of x and the details of the layer directly? I think there may be a mismatch between your data dimensions and the number of channels in the network layer.

**Comment by czifan** [comment]
> inputs=torch.Size([2, 10, 1, 128, 128])
> outputs=torch.Size([2, 10, 1, 128, 128])
> 2=batch_size
> 10=time
> 128, 128=data
> data=64_64 or 128_128 or 256_256 or 512_512

Could you print out the shape of x and the details of the layer directly? I think there may be a mismatch between your data dimensions and the number of channels in the network layer.

**Comment by czifan** [comment]
> Hello,
> I am trying to integrate your convLSTM cell into my data.
> I did this in the following way (Decoder):
> ![decoder-error-1](https://user-images.githubusercontent.com/39581678/88885695-f3b4b600-d273-11ea-9963-b221e5c21b93.PNG)
> 
> but It will report an error halfway through.
> Here’s the error:
> ![decoder-error-2](https://user-images.githubusercontent.com/39581678/88885899-527a2f80-d274-11ea-856f-fab5f966d331.PNG)
> 
> As shown above, test_data has the shape: torch.Size([88, 6, 1, 241, 241])
> 
> Am I misunderstanding something?
> What is supposed to happen here?
> 
> Thanks for any help :-D

Could you print out the shape of x and the details of the layer directly? I think there may be a mismatch between your data dimensions and the number of channels in the network layer.

**Comment by dreamsfly900** [comment]
X=torch.Size([2, 10, 64, 32, 32])

**Comment by dreamsfly900** [comment]
inputs=torch.Size([2, 10, 1, 128, 128])
outputs=torch.Size([2, 10, 1, 128, 128])
2=batch_size
10=time
128, 128=data

X=torch.Size([2, 10, 64, 32, 32])

**Comment by dreamsfly900** [comment]
![QQ图片20200730142046](https://user-images.githubusercontent.com/22961490/88887905-e1387d80-d26f-11ea-91d0-35270e1b859b.png)

**Comment by czifan** [comment]
Have you modified the network structure of the corresponding configuration file under the "configs" directory? I have tried it, it should be the network channel number setting problem.

**Comment by SojeongAn** [comment]
Hello. What you explained helped me solve the problem.
I also found and fixed two big bugs in my code from the outside as follow:

1. There was a problem with the size of my data
2. I got an incorrect return of encoding due to a syntax error (decoded it without encoding).

Thanks for the help 👍

**Comment by czifan** [comment]
I'm glad I could help you solve the problem!

**Comment by SojeongAn** [comment]
Thanks. 
Your code helped me understand the paper.

But I have a one more question. 
In the 'main.py' file, it seems that 'valid records' and 'test records' are array type. 

![main](https://user-images.githubusercontent.com/39581678/89160746-83c46980-d5ac-11ea-8fe0-79f54e45fcd8.PNG)


Is it correct to append it after returning as a dictionary value?
I changed this to a different variable.
