### ISSUE TITLE
A bug in main method.

### ISSUE THREAD

**Issue by SmallSquare** [czifan/ConvLSTM.pytorch#2]
In the main() method, I found following codes:

https://github.com/czifan/ConvLSTM.pytorch/blob/7225cb6db82413a172973ca363ce2115d9120a31/main.py#L53-L60

You used these 3 lists to store the result of losses, and I think you may wanna use the "epoch_records" to store temporary results. Those 3 lists are for final results, epoch_records(as a dict) is for temporary results, right?
It may be a tiny mistake.

**Comment by czifan** [comment]
> In the main() method, I found following codes:
> 
> https://github.com/czifan/ConvLSTM.pytorch/blob/7225cb6db82413a172973ca363ce2115d9120a31/main.py#L53-L60
> 
> You used these 3 lists to store the result of losses, and I think you may wanna use the "epoch_records" to store temporary results. Those 3 lists are for final results, epoch_records(as a dict) is for temporary results, right?
> It may be a tiny mistake.

Thanks for pointing out this mistake! I have corrected it.
